insert into T_USER_DETAILS column(UD_USER_ID, UD_FIRST_NAME, UD_LAST_NAME, UD_EMPLOYEE_ID, UD_PROJECT_ID, UD_TASK_ID) values(100,'Sourav','Sinha',123456,null,null);
insert into T_USER_DETAILS column(UD_USER_ID, UD_FIRST_NAME, UD_LAST_NAME, UD_EMPLOYEE_ID, UD_PROJECT_ID, UD_TASK_ID) values(200,'Soumen','Saha',223456,null,null);
insert into T_USER_DETAILS column(UD_USER_ID, UD_FIRST_NAME, UD_LAST_NAME, UD_EMPLOYEE_ID, UD_PROJECT_ID, UD_TASK_ID) values(300,'Soumi','Nath',323456,null,null);
insert into T_USER_DETAILS column(UD_USER_ID, UD_FIRST_NAME, UD_LAST_NAME, UD_EMPLOYEE_ID, UD_PROJECT_ID, UD_TASK_ID) values(400,'Mukesh','Agrawal',423456,null,null);

insert into T_PROJECT_DETAILS column(PD_PROJECT_ID, PD_PROJECT, PD_START_DATE, PD_END_DATE, PD_PRIORITY) values(100,'RSA','2005-07-28','2020-07-27',9);
insert into T_PROJECT_DETAILS column(PD_PROJECT_ID, PD_PROJECT, PD_START_DATE, PD_END_DATE, PD_PRIORITY) values(200,'IFDS','2010-07-28','2015-07-27',19);
insert into T_PROJECT_DETAILS column(PD_PROJECT_ID, PD_PROJECT, PD_START_DATE, PD_END_DATE, PD_PRIORITY) values(300,'MLIFE','2013-07-28','2025-07-27',11);
insert into T_PROJECT_DETAILS column(PD_PROJECT_ID, PD_PROJECT, PD_START_DATE, PD_END_DATE, PD_PRIORITY) values(400,'BANK OF AMERICA','2000-07-28','2030-07-27',26);